// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.stamhe.springboot.user.proto;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stamhe.springboot.user.proto.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>fixed64 UserId = 1;</code>
   */
  long getUserId();
}
