// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: User.proto

package com.stamhe.springboot.user.proto;

public final class UserOuter {
  private UserOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stamhe_springboot_user_proto_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stamhe_springboot_user_proto_UserRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nUser.proto\022 com.stamhe.springboot.user" +
      ".proto\032\014Common.proto\"\035\n\013UserRequest\022\016\n\006U" +
      "serId\030\001 \001(\0062t\n\004User\022l\n\010UserInfo\022-.com.st" +
      "amhe.springboot.user.proto.UserRequest\032/" +
      ".com.stamhe.springboot.common.proto.Comm" +
      "onReply\"\000B/\n com.stamhe.springboot.user." +
      "protoB\tUserOuterP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stamhe.springboot.common.proto.CommonOuter.getDescriptor(),
        }, assigner);
    internal_static_com_stamhe_springboot_user_proto_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stamhe_springboot_user_proto_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stamhe_springboot_user_proto_UserRequest_descriptor,
        new java.lang.String[] { "UserId", });
    com.stamhe.springboot.common.proto.CommonOuter.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
