<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Common.proto

namespace GPBMetadata;

class Common
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aab010a0c436f6d6d6f6e2e70726f746f1222636f6d2e7374616d68652e" .
            "737072696e67626f6f742e636f6d6d6f6e2e70726f746f223a0a0b436f6d" .
            "6d6f6e5265706c79120f0a074d657373616765180120012809120c0a0443" .
            "6f6465180220012805120c0a044461746118032001280942330a22636f6d" .
            "2e7374616d68652e737072696e67626f6f742e636f6d6d6f6e2e70726f74" .
            "6f420b436f6d6d6f6e4f757465725001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

