<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto

namespace GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afc010a0a557365722e70726f746f1220636f6d2e7374616d68652e7370" .
            "72696e67626f6f742e757365722e70726f746f221d0a0b55736572526571" .
            "75657374120e0a0655736572496418012001280632740a0455736572126c" .
            "0a0855736572496e666f122d2e636f6d2e7374616d68652e737072696e67" .
            "626f6f742e757365722e70726f746f2e55736572526571756573741a2f2e" .
            "636f6d2e7374616d68652e737072696e67626f6f742e636f6d6d6f6e2e70" .
            "726f746f2e436f6d6d6f6e5265706c792200422f0a20636f6d2e7374616d" .
            "68652e737072696e67626f6f742e757365722e70726f746f420955736572" .
            "4f757465725001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

