// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package com.stamhe.springboot.common.proto;

public interface CommonReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stamhe.springboot.common.proto.CommonReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string Message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 Code = 2;</code>
   */
  int getCode();

  /**
   * <code>string Data = 3;</code>
   */
  java.lang.String getData();
  /**
   * <code>string Data = 3;</code>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
